package com.joanzapata.iconify.fonts;

import com.joanzapata.iconify.Icon;

public enum EntypoIcons implements Icon {
    entypo_github('\ue600', false),
    entypo_github_with_circle('\ue601', false),
    entypo_flickr('\ue602', false),
    entypo_flickr_with_circle('\ue603', false),
    entypo_youtube_with_circle('\ue604', false),
    entypo_youtube('\ue605', false),
    entypo_vimeo('\ue606', false),
    entypo_vimeo_with_circle('\ue607', false),
    entypo_twitter_with_circle('\ue608', false),
    entypo_twitter('\ue609', false),
    entypo_facebook('\ue60a', false),
    entypo_facebook_with_circle('\ue60b', false),
    entypo_google_with_circle('\ue60c', false),
    entypo_google('\ue60d', false),
    entypo_instagram('\ue60e', false),
    entypo_instagram_with_circle('\ue60f', false),
    entypo_pinterest_with_circle('\ue610', false),
    entypo_pinterest('\ue611', false),
    entypo_tumblr('\ue612', false),
    entypo_tumblr_with_circle('\ue613', false),
    entypo_linkedin_with_circle('\ue614', false),
    entypo_dribbble('\ue615', false),
    entypo_dribbble_with_circle('\ue616', false),
    entypo_stumbleupon('\ue617', false),
    entypo_stumbleupon_with_circle('\ue618', false),
    entypo_lastfm_with_circle('\ue619', false),
    entypo_lastfm('\ue61a', false),
    entypo_rdio('\ue61b', false),
    entypo_rdio_with_circle('\ue61c', false),
    entypo_spotify('\ue61d', false),
    entypo_spotify_with_circle('\ue61e', false),
    entypo_vk('\ue61f', false),
    entypo_vk_alternitive('\ue620', false),
    entypo_vk_with_circle('\ue621', false),
    entypo_vine('\ue622', false),
    entypo_vine_with_circle('\ue623', false),
    entypo_xing('\ue624', false),
    entypo_xing_with_circle('\ue625', false),
    entypo_px('\ue626', false),
    entypo_px_with_circle('\ue627', false),
    entypo_skype('\ue628', false),
    entypo_skype_with_circle('\ue629', false),
    entypo_yelp('\ue62a', false),
    entypo_grooveshark('\ue62b', false),
    entypo_icloud('\ue62c', false),
    entypo_dropbox('\ue62d', false),
    entypo_onedrive('\ue62e', false),
    entypo_qq('\ue62f', false),
    entypo_google_hangouts('\ue630', false),
    entypo_slideshare('\ue631', false),
    entypo_flattr('\ue632', false),
    entypo_foursquare('\ue633', false),
    entypo_scribd('\ue634', false),
    entypo_swarm('\ue635', false),
    entypo_renren('\ue636', false),
    entypo_sina_weibo('\ue637', false),
    entypo_google_drive('\ue638', false),
    entypo_picasa('\ue639', false),
    entypo_soundcloud('\ue63a', false),
    entypo_mixi('\ue63b', false),
    entypo_behance('\ue63c', false),
    entypo_paypal('\ue63d', false),
    entypo_smashing('\ue63e', false),
    entypo_creative_cloud('\ue63f', false),
    entypo_basecamp('\ue640', false),
    entypo_tripadvisor('\ue641', false),
    entypo_rainbow('\ue642'),
    entypo_youko('\ue643', false),
    entypo_youko_with_circle('\ue644', false),
    entypo_qq_with_circle('\ue645', false),
    entypo_raft('\ue646', false),
    entypo_raft_with_circle('\ue647', false),
    entypo_medium_with_circle('\ue648', false),
    entypo_medium('\ue649', false),
    entypo_mail_with_circle('\ue64a'),
    entypo_app_store('\ue64b', false),
    entypo_google_play('\ue64c', false),
    entypo_windows_store('\ue64d', false),
    entypo_houzz('\ue64e', false),
    entypo_baidu('\ue64f', false),
    entypo_evernote('\ue650', false),
    entypo_linkedin('\ue651', false),
    entypo_add_user('\ue652'),
    entypo_v_card('\ue653'),
    entypo_users('\ue654'),
    entypo_user('\ue655'),
    entypo_thumbs_up('\ue656'),
    entypo_thumbs_down('\ue657'),
    entypo_tablet('\ue658'),
    entypo_star('\ue659'),
    entypo_star_outlined('\ue65a'),
    entypo_shareable('\ue65b'),
    entypo_share('\ue65c'),
    entypo_share_alternative('\ue65d'),
    entypo_reply('\ue65e'),
    entypo_reply_all('\ue65f'),
    entypo_phone('\ue660'),
    entypo_paper_plane('\ue661'),
    entypo_old_phone('\ue662'),
    entypo_old_mobile('\ue663', false),
    entypo_notification('\ue664'),
    entypo_new_message('\ue665', false),
    entypo_mouse('\ue666', false),
    entypo_mobile('\ue667'),
    entypo_map('\ue668'),
    entypo_mail('\ue669'),
    entypo_location('\ue66a'),
    entypo_location_pin('\ue66b'),
    entypo_laptop('\ue66c'),
    entypo_landline('\ue66d', false),
    entypo_inbox('\ue66e'),
    entypo_heart('\ue66f'),
    entypo_heart_outlined('\ue670'),
    entypo_hair_cross('\ue671'),
    entypo_forward('\ue672'),
    entypo_feather('\ue673'),
    entypo_export('\ue674'),
    entypo_email('\ue675', false),
    entypo_edit('\ue676', false),
    entypo_direction('\ue677'),
    entypo_compass('\ue678'),
    entypo_chat('\ue679'),
    entypo_attachment('\ue67a'),
    entypo_address('\ue67b'),
    entypo_message('\ue67c'),
    entypo_typing('\ue67d'),
    entypo_quote('\ue67e'),
    entypo_home('\ue67f'),
    entypo_popup('\ue680'),
    entypo_magnifying_glass('\ue681', false),
    entypo_flashlight('\ue682'),
    entypo_calculator('\ue683'),
    entypo_print('\ue684'),
    entypo_bell('\ue685'),
    entypo_link('\ue686'),
    entypo_flag('\ue687'),
    entypo_cog('\ue688'),
    entypo_tools('\ue689', false),
    entypo_trophy('\ue68a'),
    entypo_power_plug('\ue68b'),
    entypo_price_tag('\ue68c'),
    entypo_camera('\ue68d', false),
    entypo_megaphone('\ue68e'),
    entypo_awareness_ribbon('\ue68f'),
    entypo_moon('\ue690'),
    entypo_palette('\ue691', false),
    entypo_leaf('\ue692'),
    entypo_man('\ue693'),
    entypo_drink('\ue694'),
    entypo_note('\ue695', false),
    entypo_beamed_note('\ue696', false),
    entypo_modern_mic('\ue697'),
    entypo_clapperboard('\ue698', false),
    entypo_price_ribbon('\ue699'),
    entypo_medal('\ue69a'),
    entypo_new('\ue69b'),
    entypo_graduation_cap('\ue69c'),
    entypo_blackboard('\ue69d'),
    entypo_book('\ue69e'),
    entypo_pin('\ue69f'),
    entypo_news('\ue6a0'),
    entypo_aircraft('\ue6a1'),
    entypo_shield('\ue6a2'),
    entypo_aircraft_take_off('\ue6a3'),
    entypo_aircraft_landing('\ue6a4'),
    entypo_lifebuoy('\ue6a5'),
    entypo_eye('\ue6a6'),
    entypo_credit('\ue6a7'),
    entypo_hand('\ue6a8', false),
    entypo_clock('\ue6a9', false),
    entypo_mic('\ue6aa'),
    entypo_flash('\ue6ab'),
    entypo_calendar('\ue6ac'),
    entypo_thunder_cloud('\ue6ad'),
    entypo_drop('\ue6ae'),
    entypo_vinyl('\ue6af'),
    entypo_bowl('\ue6b0', false),
    entypo_briefcase('\ue6b1'),
    entypo_air('\ue6b2'),
    entypo_hour_glass('\ue6b3'),
    entypo_tree('\ue6b4'),
    entypo_gauge('\ue6b5', false),
    entypo_colours('\ue6b6'),
    entypo_language('\ue6b7', false),
    entypo_network('\ue6b8'),
    entypo_key('\ue6b9', false),
    entypo_stopwatch('\ue6ba', false),
    entypo_battery('\ue6bb'),
    entypo_bucket('\ue6bc'),
    entypo_funnel('\ue6bd'),
    entypo_magnet('\ue6be'),
    entypo_cake('\ue6bf'),
    entypo_drive('\ue6c0'),
    entypo_game_controller('\ue6c1', false),
    entypo_cup('\ue6c2'),
    entypo_rocket('\ue6c3'),
    entypo_lab_flask('\ue6c4'),
    entypo_ruler('\ue6c5'),
    entypo_brush('\ue6c6', false),
    entypo_suitcase('\ue6c7'),
    entypo_traffic_cone('\ue6c8'),
    entypo_globe('\ue6c9', false),
    entypo_radio('\ue6ca', false),
    entypo_keyboard('\ue6cb', false),
    entypo_round_brush('\ue6cc', false),
    entypo_flat_brush('\ue6cd', false),
    entypo_pencil('\ue6ce', false),
    entypo_eraser('\ue6cf', false),
    entypo_scissors('\ue6d0'),
    entypo_browser('\ue6d1', false),
    entypo_publish('\ue6d2', false),
    entypo_progress_full('\ue6d3'),
    entypo_progress_two('\ue6d4'),
    entypo_progress_one('\ue6d5'),
    entypo_progress_empty('\ue6d6'),
    entypo_light_down('\ue6d7'),
    entypo_light_up('\ue6d8'),
    entypo_adjust('\ue6d9'),
    entypo_sound_mix('\ue6da'),
    entypo_code('\ue6db', false),
    entypo_tv('\ue6dc'),
    entypo_infinity('\ue6dd'),
    entypo_light_bulb('\ue6de'),
    entypo_credit_card('\ue6df', false),
    entypo_shop('\ue6e0'),
    entypo_shopping_cart('\ue6e1'),
    entypo_shopping_bag('\ue6e2'),
    entypo_shopping_basket('\ue6e3', false),
    entypo_wallet('\ue6e4', false),
    entypo_dial_pad('\ue6e5'),
    entypo_voicemail('\ue6e6'),
    entypo_clipboard('\ue6e7'),
    entypo_database('\ue6e8'),
    entypo_box('\ue6e9'),
    entypo_ticket('\ue6ea'),
    entypo_rss('\ue6eb'),
    entypo_signal('\ue6ec'),
    entypo_thermometer('\ue6ed'),
    entypo_water('\ue6ee'),
    entypo_sweden('\ue6ef', false),
    entypo_line_graph('\ue6f0'),
    entypo_pie_chart('\ue6f1'),
    entypo_bar_graph('\ue6f2'),
    entypo_area_graph('\ue6f3'),
    entypo_circular_graph('\ue6f4'),
    entypo_lock('\ue6f5'),
    entypo_lock_open('\ue6f6'),
    entypo_login('\ue6f7'),
    entypo_log_out('\ue6f8'),
    entypo_switch('\ue6f9'),
    entypo_check('\ue6fa', false),
    entypo_cross('\ue6fb'),
    entypo_squared_minus('\ue6fc'),
    entypo_squared_plus('\ue6fd'),
    entypo_squared_cross('\ue6fe'),
    entypo_circle_with_minus('\ue6ff'),
    entypo_circle_with_plus('\ue700'),
    entypo_circle_with_cross('\ue701'),
    entypo_minus('\ue702'),
    entypo_plus('\ue703'),
    entypo_erase('\ue704'),
    entypo_block('\ue705'),
    entypo_info('\ue706', false),
    entypo_help('\ue707'),
    entypo_help_with_circle('\ue708'),
    entypo_info_with_circle('\ue709', false),
    entypo_cycle('\ue70a'),
    entypo_ccw('\ue70b', false),
    entypo_cw('\ue70c', false),
    entypo_circle('\ue70d'),
    entypo_shuffle('\ue70e', false),
    entypo_back('\ue70f'),
    entypo_level_down('\ue710'),
    entypo_level_up('\ue711'),
    entypo_loop('\ue712'),
    entypo_retweet('\ue713'),
    entypo_swap('\ue714'),
    entypo_back_in_time('\ue715', false),
    entypo_align_left('\ue716', false),
    entypo_align_bottom('\ue717', false),
    entypo_align_top('\ue718', false),
    entypo_align_right('\ue719', false),
    entypo_align_horizontal_middle('\ue71a', false),
    entypo_align_vertical_middle('\ue71b', false),
    entypo_tag('\ue71c'),
    entypo_untag('\ue71d'),
    entypo_emoji_happy('\ue71e'),
    entypo_emoji_neutral('\ue71f'),
    entypo_emoji_sad('\ue720'),
    entypo_unread('\ue721'),
    entypo_text('\ue722'),
    entypo_list('\ue723'),
    entypo_grid('\ue724'),
    entypo_menu('\ue725'),
    entypo_document('\ue726'),
    entypo_documents('\ue727'),
    entypo_text_document('\ue728'),
    entypo_text_document_inverted('\ue729'),
    entypo_spreadsheet('\ue72a'),
    entypo_copy('\ue72b'),
    entypo_image('\ue72c'),
    entypo_image_inverted('\ue72d'),
    entypo_images('\ue72e'),
    entypo_video('\ue72f', false),
    entypo_music('\ue730', false),
    entypo_folder('\ue731'),
    entypo_folder_images('\ue732'),
    entypo_folder_music('\ue733', false),
    entypo_folder_video('\ue734', false),
    entypo_sports_club('\ue735'),
    entypo_mask('\ue736'),
    entypo_time_slot('\ue737', false),
    entypo_archive('\ue738'),
    entypo_emoji_flirt('\ue739'),
    entypo_trash('\ue73a'),
    entypo_upload('\ue73b'),
    entypo_download('\ue73c'),
    entypo_save('\ue73d', false),
    entypo_install('\ue73e'),
    entypo_uninstall('\ue73f'),
    entypo_cloud('\ue740'),
    entypo_upload_to_cloud('\ue741'),
    entypo_layers('\ue742'),
    entypo_bookmark('\ue743'),
    entypo_bookmarks('\ue744'),
    entypo_open_book('\ue745', false),
    entypo_controller_play('\ue746', false),
    entypo_controller_paus('\ue747', false),
    entypo_controller_record('\ue748', false),
    entypo_controller_stop('\ue749', false),
    entypo_controller_fast_forward('\ue74a', false),
    entypo_controller_jump_to_start('\ue74b', false),
    entypo_controller_next('\ue74c', false),
    entypo_resize_full_screen('\ue74d', false),
    entypo_resize_100('\ue74e', false),
    entypo_controller_volume('\ue74f', false),
    entypo_sound('\ue750'),
    entypo_sound_mute('\ue751'),
    entypo_flow_cascade('\ue752'),
    entypo_flow_branch('\ue753'),
    entypo_flow_tree('\ue754'),
    entypo_flow_line('\ue755'),
    entypo_flow_parallel('\ue756'),
    entypo_arrow_bold_left('\ue757'),
    entypo_arrow_bold_down('\ue758'),
    entypo_arrow_bold_up('\ue759'),
    entypo_arrow_bold_right('\ue75a'),
    entypo_arrow_left('\ue75b'),
    entypo_arrow_down('\ue75c'),
    entypo_arrow_up('\ue75d'),
    entypo_arrow_right('\ue75e'),
    entypo_arrow_with_circle_left('\ue75f'),
    entypo_arrow_with_circle_down('\ue760'),
    entypo_arrow_with_circle_up('\ue761'),
    entypo_arrow_with_circle_right('\ue762'),
    entypo_triangle_left('\ue763'),
    entypo_triangle_down('\ue764'),
    entypo_triangle_up('\ue765'),
    entypo_triangle_right('\ue766'),
    entypo_chevron_left('\ue767'),
    entypo_chevron_down('\ue768'),
    entypo_chevron_up('\ue769'),
    entypo_chevron_right('\ue76a'),
    entypo_chevron_small_left('\ue76b'),
    entypo_chevron_small_down('\ue76c'),
    entypo_chevron_small_up('\ue76d'),
    entypo_chevron_small_right('\ue76e'),
    entypo_chevron_thin_left('\ue76f'),
    entypo_chevron_thin_down('\ue770'),
    entypo_chevron_thin_up('\ue771'),
    entypo_chevron_thin_right('\ue772'),
    entypo_chevron_with_circle_left('\ue773'),
    entypo_chevron_with_circle_down('\ue774'),
    entypo_chevron_with_circle_up('\ue775'),
    entypo_chevron_with_circle_right('\ue776'),
    entypo_arrow_long_left('\ue777'),
    entypo_arrow_long_down('\ue778'),
    entypo_arrow_long_up('\ue779'),
    entypo_arrow_long_right('\ue77a'),
    entypo_select_arrows('\ue77b'),
    entypo_dots_three_vertical('\ue77c'),
    entypo_dots_two_vertical('\ue77d'),
    entypo_dot_single('\ue77e'),
    entypo_dots_two_horizontal('\ue77f'),
    entypo_dots_three_horizontal('\ue780'),
    entypo_add_to_list('\ue781'),
    entypo_controller_fast_backward('\ue782', false),
    entypo_remove_user('\ue783'),
    entypo_classic_computer('\ue784', false),
    entypo_document_landscape('\ue785'),
    entypo_warning('\ue786'),
    entypo_merge('\ue787'),
    entypo_eye_with_line('\ue788'),
    entypo_flower('\ue789'),
    entypo_newsletter('\ue78a'),
    entypo_tablet_mobile_combo('\ue78b'),
    entypo_bug('\ue78c'),
    entypo_video_camera('\ue78d'),
    entypo_fingerprint('\ue78e'),
    entypo_mouse_pointer('\ue78f', false),
    entypo_crop('\ue790'),
    entypo_notifications_off('\ue791'),
    entypo_creative_commons_attribution('\ue792', false),
    entypo_creative_commons('\ue793', false),
    entypo_creative_commons_sharealike('\ue794', false),
    entypo_creative_commons_share('\ue795', false),
    entypo_creative_commons_remix('\ue796', false),
    entypo_creative_commons_public_domain('\ue797', false),
    entypo_creative_commons_noncommercial_us('\ue798', false),
    entypo_creative_commons_noncommercial_eu('\ue799', false),
    entypo_creative_commons_noderivs('\ue79a', false);

    private final char character;
    private final boolean supportsRtl;

    EntypoIcons(char character) {
        this(character, true);
    }

    EntypoIcons(char character, boolean supportsRtl) {
        this.character = character;
        this.supportsRtl = supportsRtl;
    }

    @Override
    public String key() {
        return name().replace('_', '-');
    }

    @Override
    public char character() {
        return character;
    }

    @Override
    public boolean supportsRtl() {
        return supportsRtl;
    }
}
