package com.joanzapata.iconify.fonts;

import com.joanzapata.iconify.Icon;

public enum MaterialCommunityIcons implements Icon {
    mdi_account('\uf101'),
    mdi_account_alert('\uf102'),
    mdi_account_box('\uf103'),
    mdi_account_box_outline('\uf104'),
    mdi_account_check('\uf105', false),
    mdi_account_circle('\uf106'),
    mdi_account_key('\uf107'),
    mdi_account_location('\uf108'),
    mdi_account_minus('\uf109'),
    mdi_account_multiple('\uf10a'),
    mdi_account_multiple_outline('\uf10b'),
    mdi_account_multiple_plus('\uf10c'),
    mdi_account_network('\uf10d'),
    mdi_account_outline('\uf10e'),
    mdi_account_plus('\uf10f'),
    mdi_account_remove('\uf110'),
    mdi_account_search('\uf111'),
    mdi_account_star('\uf112'),
    mdi_account_star_variant('\uf113'),
    mdi_account_switch('\uf114'),
    mdi_airballoon('\uf115'),
    mdi_airplane('\uf116'),
    mdi_airplane_off('\uf117'),
    mdi_alarm('\uf118', false),
    mdi_alarm_check('\uf119', false),
    mdi_alarm_multiple('\uf11a', false),
    mdi_alarm_off('\uf11b'),
    mdi_alarm_plus('\uf11c'),
    mdi_album('\uf11d'),
    mdi_alert('\uf11e'),
    mdi_alert_box('\uf11f'),
    mdi_alert_circle('\uf120'),
    mdi_alert_octagon('\uf121'),
    mdi_alpha('\uf122', false),
    mdi_alphabetical('\uf123', false),
    mdi_amazon('\uf124', false),
    mdi_amazon_clouddrive('\uf125', false),
    mdi_ambulance('\uf126'),
    mdi_android('\uf127', false),
    mdi_android_debug_bridge('\uf128', false),
    mdi_android_studio('\uf129', false),
    mdi_apple('\uf12a', false),
    mdi_apple_finder('\uf12b', false),
    mdi_apple_ios('\uf12c', false),
    mdi_apple_mobileme('\uf12d', false),
    mdi_apple_safari('\uf12e', false),
    mdi_appnet('\uf12f', false),
    mdi_apps('\uf130'),
    mdi_archive('\uf131'),
    mdi_arrange_bring_forward('\uf132'),
    mdi_arrange_bring_to_front('\uf133'),
    mdi_arrange_send_backward('\uf134'),
    mdi_arrange_send_to_back('\uf135'),
    mdi_arrow_all('\uf136'),
    mdi_arrow_bottom_left('\uf137'),
    mdi_arrow_bottom_right('\uf138'),
    mdi_arrow_collapse('\uf139'),
    mdi_arrow_down('\uf13a'),
    mdi_arrow_down_bold('\uf13b'),
    mdi_arrow_down_bold_circle('\uf13c'),
    mdi_arrow_down_bold_circle_outline('\uf13d'),
    mdi_arrow_down_bold_hexagon_outline('\uf13e'),
    mdi_arrow_expand('\uf13f'),
    mdi_arrow_left('\uf140'),
    mdi_arrow_left_bold('\uf141'),
    mdi_arrow_left_bold_circle('\uf142'),
    mdi_arrow_left_bold_circle_outline('\uf143'),
    mdi_arrow_left_bold_hexagon_outline('\uf144'),
    mdi_arrow_right('\uf145'),
    mdi_arrow_right_bold('\uf146'),
    mdi_arrow_right_bold_circle('\uf147'),
    mdi_arrow_right_bold_circle_outline('\uf148'),
    mdi_arrow_right_bold_hexagon_outline('\uf149'),
    mdi_arrow_top_left('\uf14a'),
    mdi_arrow_top_right('\uf14b'),
    mdi_arrow_up('\uf14c'),
    mdi_arrow_up_bold('\uf14d'),
    mdi_arrow_up_bold_circle('\uf14e'),
    mdi_arrow_up_bold_circle_outline('\uf14f'),
    mdi_arrow_up_bold_hexagon_outline('\uf150'),
    mdi_at('\uf151', false),
    mdi_attachment('\uf152'),
    mdi_audiobook('\uf153', false),
    mdi_auto_fix('\uf154'),
    mdi_auto_upload('\uf155', false),
    mdi_baby('\uf156'),
    mdi_backburger('\uf157'),
    mdi_backup_restore('\uf158'),
    mdi_bank('\uf159'),
    mdi_barcode('\uf15a'),
    mdi_barley('\uf15b'),
    mdi_barrel('\uf15c'),
    mdi_basecamp('\uf15d', false),
    mdi_basket('\uf15e'),
    mdi_basket_fill('\uf15f'),
    mdi_basket_unfill('\uf160'),
    mdi_battery('\uf161'),
    mdi_battery_10('\uf162'),
    mdi_battery_20('\uf163'),
    mdi_battery_30('\uf164'),
    mdi_battery_40('\uf165'),
    mdi_battery_50('\uf166'),
    mdi_battery_60('\uf167'),
    mdi_battery_70('\uf168'),
    mdi_battery_80('\uf169'),
    mdi_battery_90('\uf16a'),
    mdi_battery_alert('\uf16b'),
    mdi_battery_charging_100('\uf16c'),
    mdi_battery_charging_20('\uf16d'),
    mdi_battery_charging_30('\uf16e'),
    mdi_battery_charging_40('\uf16f'),
    mdi_battery_charging_60('\uf170'),
    mdi_battery_charging_80('\uf171'),
    mdi_battery_charging_90('\uf172'),
    mdi_battery_minus('\uf173'),
    mdi_battery_negative('\uf174'),
    mdi_battery_outline('\uf175'),
    mdi_battery_plus('\uf176'),
    mdi_battery_positive('\uf177'),
    mdi_battery_unknown('\uf178'),
    mdi_beach('\uf179'),
    mdi_beaker('\uf17a'),
    mdi_beaker_empty('\uf17b'),
    mdi_beaker_empty_outline('\uf17c'),
    mdi_beaker_outline('\uf17d'),
    mdi_beats('\uf17e', false),
    mdi_beer('\uf17f'),
    mdi_behance('\uf180', false),
    mdi_bell('\uf181'),
    mdi_bell_off('\uf182'),
    mdi_bell_outline('\uf183'),
    mdi_bell_ring('\uf184'),
    mdi_bell_ring_outline('\uf185'),
    mdi_bell_sleep('\uf186', false),
    mdi_beta('\uf187', false),
    mdi_bike('\uf188'),
    mdi_bing('\uf189', false),
    mdi_binoculars('\uf18a'),
    mdi_bio('\uf18b', false),
    mdi_biohazard('\uf18c'),
    mdi_bitbucket('\uf18d', false),
    mdi_black_mesa('\uf18e', false),
    mdi_blackberry('\uf18f', false),
    mdi_blinds('\uf190'),
    mdi_block_helper('\uf191'),
    mdi_blogger('\uf192', false),
    mdi_bluetooth('\uf193', false),
    mdi_bluetooth_audio('\uf194', false),
    mdi_bluetooth_connect('\uf195', false),
    mdi_bluetooth_settings('\uf196', false),
    mdi_bluetooth_transfer('\uf197', false),
    mdi_blur('\uf198'),
    mdi_blur_linear('\uf199'),
    mdi_blur_off('\uf19a'),
    mdi_blur_radial('\uf19b'),
    mdi_bone('\uf19c'),
    mdi_book('\uf19d'),
    mdi_book_multiple('\uf19e'),
    mdi_book_multiple_variant('\uf19f'),
    mdi_book_open('\uf1a0'),
    mdi_book_variant('\uf1a1'),
    mdi_bookmark('\uf1a2'),
    mdi_bookmark_check('\uf1a3', false),
    mdi_bookmark_music('\uf1a4', false),
    mdi_bookmark_outline('\uf1a5'),
    mdi_bookmark_outline_plus('\uf1a6'),
    mdi_bookmark_plus('\uf1a7'),
    mdi_bookmark_remove('\uf1a8'),
    mdi_border_all('\uf1a9'),
    mdi_border_bottom('\uf1aa'),
    mdi_border_color('\uf1ab', false),
    mdi_border_horizontal('\uf1ac'),
    mdi_border_inside('\uf1ad'),
    mdi_border_left('\uf1ae', false),
    mdi_border_none('\uf1af'),
    mdi_border_outside('\uf1b0'),
    mdi_border_right('\uf1b1', false),
    mdi_border_top('\uf1b2'),
    mdi_border_vertical('\uf1b3'),
    mdi_bowling('\uf1b4'),
    mdi_box('\uf1b5', false),
    mdi_briefcase('\uf1b6'),
    mdi_briefcase_check('\uf1b7', false),
    mdi_briefcase_download('\uf1b8'),
    mdi_briefcase_upload('\uf1b9'),
    mdi_brightness_1('\uf1ba'),
    mdi_brightness_2('\uf1bb'),
    mdi_brightness_3('\uf1bc'),
    mdi_brightness_4('\uf1bd'),
    mdi_brightness_5('\uf1be'),
    mdi_brightness_6('\uf1bf'),
    mdi_brightness_7('\uf1c0'),
    mdi_brightness_auto('\uf1c1'),
    mdi_broom('\uf1c2', false),
    mdi_brush('\uf1c3', false),
    mdi_bug('\uf1c4'),
    mdi_bulletin_board('\uf1c5'),
    mdi_bullhorn('\uf1c6'),
    mdi_bus('\uf1c7'),
    mdi_cake('\uf1c8'),
    mdi_cake_variant('\uf1c9'),
    mdi_calculator('\uf1ca'),
    mdi_calendar('\uf1cb', false),
    mdi_calendar_blank('\uf1cc'),
    mdi_calendar_check('\uf1cd', false),
    mdi_calendar_clock('\uf1ce', false),
    mdi_calendar_multiple('\uf1cf', false),
    mdi_calendar_multiple_check('\uf1d0', false),
    mdi_calendar_plus('\uf1d1'),
    mdi_calendar_remove('\uf1d2'),
    mdi_calendar_text('\uf1d3'),
    mdi_calendar_today('\uf1d4', false),
    mdi_camcorder('\uf1d5'),
    mdi_camcorder_box('\uf1d6'),
    mdi_camcorder_box_off('\uf1d7'),
    mdi_camcorder_off('\uf1d8'),
    mdi_camera('\uf1d9'),
    mdi_camera_front('\uf1da'),
    mdi_camera_front_variant('\uf1db'),
    mdi_camera_iris('\uf1dc'),
    mdi_camera_party_mode('\uf1dd'),
    mdi_camera_rear('\uf1de'),
    mdi_camera_rear_variant('\uf1df'),
    mdi_camera_switch('\uf1e0'),
    mdi_camera_timer('\uf1e1', false),
    mdi_candycane('\uf1e2'),
    mdi_car('\uf1e3'),
    mdi_car_wash('\uf1e4'),
    mdi_carrot('\uf1e5'),
    mdi_cart('\uf1e6'),
    mdi_cart_outline('\uf1e7'),
    mdi_cash('\uf1e8'),
    mdi_cash_100('\uf1e9', false),
    mdi_cash_multiple('\uf1ea'),
    mdi_cash_usd('\uf1eb', false),
    mdi_cast('\uf1ec'),
    mdi_cast_connected('\uf1ed'),
    mdi_castle('\uf1ee'),
    mdi_cat('\uf1ef'),
    mdi_cellphone('\uf1f0'),
    mdi_cellphone_android('\uf1f1'),
    mdi_cellphone_dock('\uf1f2'),
    mdi_cellphone_iphone('\uf1f3'),
    mdi_cellphone_link('\uf1f4'),
    mdi_cellphone_link_off('\uf1f5'),
    mdi_cellphone_settings('\uf1f6'),
    mdi_chair_school('\uf1f7'),
    mdi_chart_arc('\uf1f8'),
    mdi_chart_areaspline('\uf1f9'),
    mdi_chart_bar('\uf1fa'),
    mdi_chart_histogram('\uf1fb'),
    mdi_chart_line('\uf1fc'),
    mdi_chart_pie('\uf1fd'),
    mdi_check('\uf1fe', false),
    mdi_check_all('\uf1ff', false),
    mdi_checkbox_blank('\uf200', false),
    mdi_checkbox_blank_circle('\uf201', false),
    mdi_checkbox_blank_circle_outline('\uf202', false),
    mdi_checkbox_blank_outline('\uf203', false),
    mdi_checkbox_marked('\uf204', false),
    mdi_checkbox_marked_circle('\uf205', false),
    mdi_checkbox_marked_circle_outline('\uf206', false),
    mdi_checkbox_marked_outline('\uf207', false),
    mdi_checkbox_multiple_blank('\uf208', false),
    mdi_checkbox_multiple_blank_outline('\uf209', false),
    mdi_checkbox_multiple_marked('\uf20a', false),
    mdi_checkbox_multiple_marked_outline('\uf20b', false),
    mdi_checkerboard('\uf20c'),
    mdi_chevron_double_down('\uf20d'),
    mdi_chevron_double_left('\uf20e'),
    mdi_chevron_double_right('\uf20f'),
    mdi_chevron_double_up('\uf210'),
    mdi_chevron_down('\uf211'),
    mdi_chevron_left('\uf212'),
    mdi_chevron_right('\uf213'),
    mdi_chevron_up('\uf214'),
    mdi_church('\uf215'),
    mdi_cisco_webex('\uf216', false),
    mdi_city('\uf217'),
    mdi_clipboard('\uf218'),
    mdi_clipboard_account('\uf219'),
    mdi_clipboard_alert('\uf21a'),
    mdi_clipboard_arrow_down('\uf21b'),
    mdi_clipboard_arrow_left('\uf21c'),
    mdi_clipboard_check('\uf21d', false),
    mdi_clipboard_outline('\uf21e'),
    mdi_clipboard_text('\uf21f'),
    mdi_clippy('\uf220', false),
    mdi_clock('\uf221', false),
    mdi_clock_fast('\uf222', false),
    mdi_close('\uf223'),
    mdi_close_box('\uf224'),
    mdi_close_box_outline('\uf225'),
    mdi_close_circle('\uf226'),
    mdi_close_circle_outline('\uf227'),
    mdi_close_network('\uf228'),
    mdi_closed_caption('\uf229', false),
    mdi_cloud('\uf22a'),
    mdi_cloud_check('\uf22b', false),
    mdi_cloud_circle('\uf22c'),
    mdi_cloud_download('\uf22d'),
    mdi_cloud_outline('\uf22e'),
    mdi_cloud_outline_off('\uf22f'),
    mdi_cloud_upload('\uf230'),
    mdi_code_array('\uf231', false),
    mdi_code_braces('\uf232', false),
    mdi_code_equal('\uf233', false),
    mdi_code_greater_than('\uf234', false),
    mdi_code_less_than('\uf235', false),
    mdi_code_less_than_or_equal('\uf236', false),
    mdi_code_not_equal('\uf237', false),
    mdi_code_not_equal_variant('\uf238', false),
    mdi_code_string('\uf239', false),
    mdi_code_tags('\uf23a', false),
    mdi_codepen('\uf23b', false),
    mdi_coffee('\uf23c', false),
    mdi_coffee_to_go('\uf23d', false),
    mdi_coin('\uf23e', false),
    mdi_color_helper('\uf23f'),
    mdi_comment('\uf240', false),
    mdi_comment_account('\uf241', false),
    mdi_comment_account_outline('\uf242', false),
    mdi_comment_alert('\uf243', false),
    mdi_comment_alert_outline('\uf244', false),
    mdi_comment_check('\uf245', false),
    mdi_comment_check_outline('\uf246', false),
    mdi_comment_multiple_outline('\uf247', false),
    mdi_comment_outline('\uf248', false),
    mdi_comment_plus_outline('\uf249', false),
    mdi_comment_processing('\uf24a', false),
    mdi_comment_processing_outline('\uf24b', false),
    mdi_comment_remove_outline('\uf24c', false),
    mdi_comment_text('\uf24d', false),
    mdi_comment_text_outline('\uf24e', false),
    mdi_compare('\uf24f'),
    mdi_compass('\uf250'),
    mdi_compass_outline('\uf251'),
    mdi_console('\uf252', false),
    mdi_content_copy('\uf253'),
    mdi_content_cut('\uf254'),
    mdi_content_duplicate('\uf255'),
    mdi_content_paste('\uf256'),
    mdi_content_save('\uf257'),
    mdi_content_save_all('\uf258'),
    mdi_contrast('\uf259', false),
    mdi_contrast_box('\uf25a', false),
    mdi_contrast_circle('\uf25b', false),
    mdi_cow('\uf25c'),
    mdi_credit_card('\uf25d'),
    mdi_credit_card_multiple('\uf25e'),
    mdi_crop('\uf25f'),
    mdi_crop_free('\uf260'),
    mdi_crop_landscape('\uf261'),
    mdi_crop_portrait('\uf262'),
    mdi_crop_square('\uf263'),
    mdi_crosshairs('\uf264'),
    mdi_crosshairs_gps('\uf265'),
    mdi_crown('\uf266'),
    mdi_cube('\uf267'),
    mdi_cube_outline('\uf268'),
    mdi_cube_unfolded('\uf269'),
    mdi_cup('\uf26a'),
    mdi_cup_water('\uf26b'),
    mdi_currency_btc('\uf26c', false),
    mdi_currency_eur('\uf26d', false),
    mdi_currency_gbp('\uf26e', false),
    mdi_currency_inr('\uf26f', false),
    mdi_currency_rub('\uf270', false),
    mdi_currency_try('\uf271', false),
    mdi_currency_usd('\uf272', false),
    mdi_cursor_default('\uf273', false),
    mdi_cursor_default_outline('\uf274', false),
    mdi_cursor_move('\uf275', false),
    mdi_cursor_pointer('\uf276', false),
    mdi_database('\uf277'),
    mdi_database_minus('\uf278'),
    mdi_database_outline('\uf279'),
    mdi_database_plus('\uf27a'),
    mdi_debug_step_into('\uf27b'),
    mdi_debug_step_out('\uf27c'),
    mdi_debug_step_over('\uf27d'),
    mdi_decimal_decrease('\uf27e', false),
    mdi_decimal_increase('\uf27f', false),
    mdi_delete('\uf280'),
    mdi_delete_variant('\uf281'),
    mdi_deskphone('\uf282', false),
    mdi_desktop_mac('\uf283'),
    mdi_desktop_tower('\uf284', false),
    mdi_details('\uf285'),
    mdi_deviantart('\uf286', false),
    mdi_diamond('\uf287'),
    mdi_dice('\uf288'),
    mdi_dice_1('\uf289'),
    mdi_dice_2('\uf28a'),
    mdi_dice_3('\uf28b'),
    mdi_dice_4('\uf28c'),
    mdi_dice_5('\uf28d'),
    mdi_dice_6('\uf28e'),
    mdi_directions('\uf28f'),
    mdi_disk_alert('\uf290'),
    mdi_disqus('\uf291', false),
    mdi_disqus_outline('\uf292', false),
    mdi_division('\uf293'),
    mdi_division_box('\uf294'),
    mdi_dns('\uf295'),
    mdi_domain('\uf296'),
    mdi_dots_horizontal('\uf297'),
    mdi_dots_vertical('\uf298'),
    mdi_download('\uf299'),
    mdi_drag('\uf29a'),
    mdi_drag_horizontal('\uf29b'),
    mdi_drag_vertical('\uf29c'),
    mdi_drawing('\uf29d'),
    mdi_drawing_box('\uf29e'),
    mdi_dribbble('\uf29f', false),
    mdi_dribbble_box('\uf2a0', false),
    mdi_drone('\uf2a1'),
    mdi_dropbox('\uf2a2', false),
    mdi_drupal('\uf2a3', false),
    mdi_duck('\uf2a4'),
    mdi_dumbbell('\uf2a5', false),
    mdi_earth('\uf2a6', false),
    mdi_earth_off('\uf2a7', false),
    mdi_edge('\uf2a8', false),
    mdi_eject('\uf2a9'),
    mdi_elevation_decline('\uf2aa'),
    mdi_elevation_rise('\uf2ab'),
    mdi_elevator('\uf2ac'),
    mdi_email('\uf2ad'),
    mdi_email_open('\uf2ae'),
    mdi_email_outline('\uf2af'),
    mdi_email_secure('\uf2b0'),
    mdi_emoticon('\uf2b1'),
    mdi_emoticon_cool('\uf2b2'),
    mdi_emoticon_devil('\uf2b3'),
    mdi_emoticon_happy('\uf2b4'),
    mdi_emoticon_neutral('\uf2b5'),
    mdi_emoticon_poop('\uf2b6'),
    mdi_emoticon_sad('\uf2b7'),
    mdi_emoticon_tongue('\uf2b8'),
    mdi_engine('\uf2b9'),
    mdi_engine_outline('\uf2ba'),
    mdi_equal('\uf2bb'),
    mdi_equal_box('\uf2bc'),
    mdi_eraser('\uf2bd', false),
    mdi_escalator('\uf2be'),
    mdi_etsy('\uf2bf', false),
    mdi_evernote('\uf2c0', false),
    mdi_exclamation('\uf2c1'),
    mdi_exit_to_app('\uf2c2'),
    mdi_export('\uf2c3'),
    mdi_eye('\uf2c4'),
    mdi_eye_off('\uf2c5'),
    mdi_eyedropper('\uf2c6', false),
    mdi_eyedropper_variant('\uf2c7', false),
    mdi_facebook('\uf2c8', false),
    mdi_facebook_box('\uf2c9', false),
    mdi_facebook_messenger('\uf2ca', false),
    mdi_factory('\uf2cb'),
    mdi_fan('\uf2cc'),
    mdi_fast_forward('\uf2cd', false),
    mdi_ferry('\uf2ce'),
    mdi_file('\uf2cf', false),
    mdi_file_cloud('\uf2d0', false),
    mdi_file_delimited('\uf2d1', false),
    mdi_file_document('\uf2d2', false),
    mdi_file_document_box('\uf2d3', false),
    mdi_file_excel('\uf2d4', false),
    mdi_file_excel_box('\uf2d5', false),
    mdi_file_find('\uf2d6', false),
    mdi_file_image('\uf2d7', false),
    mdi_file_image_box('\uf2d8', false),
    mdi_file_multiple('\uf2d9', false),
    mdi_file_music('\uf2da', false),
    mdi_file_outline('\uf2db', false),
    mdi_file_pdf('\uf2dc', false),
    mdi_file_pdf_box('\uf2dd', false),
    mdi_file_powerpoint('\uf2de', false),
    mdi_file_powerpoint_box('\uf2df', false),
    mdi_file_presentation_box('\uf2e0', false),
    mdi_file_video('\uf2e1', false),
    mdi_file_word('\uf2e2', false),
    mdi_file_word_box('\uf2e3', false),
    mdi_file_xml('\uf2e4', false),
    mdi_film('\uf2e5'),
    mdi_filmstrip('\uf2e6'),
    mdi_filmstrip_off('\uf2e7'),
    mdi_filter('\uf2e8'),
    mdi_filter_outline('\uf2e9'),
    mdi_filter_remove('\uf2ea'),
    mdi_filter_remove_outline('\uf2eb'),
    mdi_filter_variant('\uf2ec'),
    mdi_fire('\uf2ed'),
    mdi_firefox('\uf2ee', false),
    mdi_fish('\uf2ef'),
    mdi_flag('\uf2f0'),
    mdi_flag_checkered('\uf2f1'),
    mdi_flag_outline('\uf2f2'),
    mdi_flag_outline_variant('\uf2f3'),
    mdi_flag_triangle('\uf2f4'),
    mdi_flag_variant('\uf2f5'),
    mdi_flash('\uf2f6'),
    mdi_flash_auto('\uf2f7'),
    mdi_flash_off('\uf2f8'),
    mdi_flashlight('\uf2f9'),
    mdi_flashlight_off('\uf2fa'),
    mdi_flattr('\uf2fb', false),
    mdi_flip_to_back('\uf2fc'),
    mdi_flip_to_front('\uf2fd'),
    mdi_floppy('\uf2fe'),
    mdi_flower('\uf2ff'),
    mdi_folder('\uf300'),
    mdi_folder_account('\uf301'),
    mdi_folder_download('\uf302'),
    mdi_folder_google_drive('\uf303'),
    mdi_folder_image('\uf304'),
    mdi_folder_lock('\uf305'),
    mdi_folder_lock_open('\uf306'),
    mdi_folder_move('\uf307'),
    mdi_folder_multiple('\uf308'),
    mdi_folder_multiple_image('\uf309'),
    mdi_folder_multiple_outline('\uf30a'),
    mdi_folder_outline('\uf30b'),
    mdi_folder_plus('\uf30c'),
    mdi_folder_remove('\uf30d'),
    mdi_folder_upload('\uf30e'),
    mdi_food('\uf30f', false),
    mdi_food_apple('\uf310'),
    mdi_food_variant('\uf311', false),
    mdi_football('\uf312'),
    mdi_football_helmet('\uf313'),
    mdi_format_align_center('\uf314', false),
    mdi_format_align_justify('\uf315', false),
    mdi_format_align_left('\uf316', false),
    mdi_format_align_right('\uf317', false),
    mdi_format_bold('\uf318', false),
    mdi_format_clear('\uf319', false),
    mdi_format_color_fill('\uf31a'),
    mdi_format_float_center('\uf31b'),
    mdi_format_float_left('\uf31c', false),
    mdi_format_float_none('\uf31d'),
    mdi_format_float_right('\uf31e', false),
    mdi_format_header_1('\uf31f', false),
    mdi_format_header_2('\uf320', false),
    mdi_format_header_3('\uf321', false),
    mdi_format_header_4('\uf322', false),
    mdi_format_header_5('\uf323', false),
    mdi_format_header_6('\uf324', false),
    mdi_format_header_decrease('\uf325', false),
    mdi_format_header_equal('\uf326', false),
    mdi_format_header_increase('\uf327', false),
    mdi_format_header_pound('\uf328', false),
    mdi_format_indent_decrease('\uf329'),
    mdi_format_indent_increase('\uf32a'),
    mdi_format_italic('\uf32b', false),
    mdi_format_line_spacing('\uf32c'),
    mdi_format_list_bulleted('\uf32d'),
    mdi_format_list_numbers('\uf32e', false),
    mdi_format_paint('\uf32f'),
    mdi_format_paragraph('\uf330', false),
    mdi_format_quote('\uf331'),
    mdi_format_size('\uf332', false),
    mdi_format_strikethrough('\uf333'),
    mdi_format_subscript('\uf334', false),
    mdi_format_superscript('\uf335', false),
    mdi_format_text('\uf336', false),
    mdi_format_textdirection_l_to_r('\uf337', false),
    mdi_format_textdirection_r_to_l('\uf338', false),
    mdi_format_underline('\uf339'),
    mdi_format_wrap_inline('\uf33a'),
    mdi_format_wrap_square('\uf33b'),
    mdi_format_wrap_tight('\uf33c'),
    mdi_format_wrap_top_bottom('\uf33d'),
    mdi_forum('\uf33e'),
    mdi_forward('\uf33f'),
    mdi_foursquare('\uf340', false),
    mdi_fridge('\uf341'),
    mdi_fullscreen('\uf342'),
    mdi_fullscreen_exit('\uf343'),
    mdi_function('\uf344', false),
    mdi_gamepad('\uf345'),
    mdi_gamepad_variant('\uf346', false),
    mdi_gas_station('\uf347', false),
    mdi_gavel('\uf348'),
    mdi_gender_female('\uf349'),
    mdi_gender_male('\uf34a'),
    mdi_gender_male_female('\uf34b'),
    mdi_gender_transgender('\uf34c'),
    mdi_gift('\uf34d'),
    mdi_git('\uf34e', false),
    mdi_github_box('\uf34f', false),
    mdi_github_circle('\uf350', false),
    mdi_glass_flute('\uf351'),
    mdi_glass_mug('\uf352'),
    mdi_glass_stange('\uf353'),
    mdi_glass_tulip('\uf354'),
    mdi_glasses('\uf355'),
    mdi_gmail('\uf356', false),
    mdi_google('\uf357', false),
    mdi_google_chrome('\uf358', false),
    mdi_google_circles('\uf359'),
    mdi_google_circles_communities('\uf35a'),
    mdi_google_circles_extended('\uf35b'),
    mdi_google_circles_group('\uf35c'),
    mdi_google_controller('\uf35d', false),
    mdi_google_controller_off('\uf35e', false),
    mdi_google_drive('\uf35f', false),
    mdi_google_earth('\uf360', false),
    mdi_google_glass('\uf361', false),
    mdi_google_maps('\uf362', false),
    mdi_google_pages('\uf363', false),
    mdi_google_play('\uf364', false),
    mdi_google_plus('\uf365', false),
    mdi_google_plus_box('\uf366', false),
    mdi_grid('\uf367'),
    mdi_grid_off('\uf368'),
    mdi_group('\uf369'),
    mdi_guitar('\uf36a'),
    mdi_guitar_pick('\uf36b'),
    mdi_guitar_pick_outline('\uf36c'),
    mdi_hand_pointing_right('\uf36d', false),
    mdi_hanger('\uf36e'),
    mdi_hangouts('\uf36f', false),
    mdi_harddisk('\uf370', false),
    mdi_headphones('\uf371'),
    mdi_headphones_box('\uf372'),
    mdi_headphones_settings('\uf373'),
    mdi_headset('\uf374'),
    mdi_headset_dock('\uf375'),
    mdi_headset_off('\uf376'),
    mdi_heart('\uf377'),
    mdi_heart_box('\uf378'),
    mdi_heart_box_outline('\uf379'),
    mdi_heart_broken('\uf37a'),
    mdi_heart_outline('\uf37b'),
    mdi_help('\uf37c'),
    mdi_help_circle('\uf37d'),
    mdi_hexagon('\uf37e'),
    mdi_hexagon_outline('\uf37f'),
    mdi_history('\uf380', false),
    mdi_hololens('\uf381'),
    mdi_home('\uf382'),
    mdi_home_modern('\uf383'),
    mdi_home_variant('\uf384'),
    mdi_hops('\uf385'),
    mdi_hospital('\uf386'),
    mdi_hospital_building('\uf387'),
    mdi_hospital_marker('\uf388'),
    mdi_hotel('\uf389'),
    mdi_houzz('\uf38a', false),
    mdi_houzz_box('\uf38b', false),
    mdi_human('\uf38c'),
    mdi_human_child('\uf38d'),
    mdi_human_male_female('\uf38e'),
    mdi_image_album('\uf38f'),
    mdi_image_area('\uf390'),
    mdi_image_area_close('\uf391'),
    mdi_image_broken('\uf392'),
    mdi_image_filter('\uf393'),
    mdi_image_filter_black_white('\uf394'),
    mdi_image_filter_center_focus('\uf395'),
    mdi_image_filter_drama('\uf396'),
    mdi_image_filter_frames('\uf397'),
    mdi_image_filter_hdr('\uf398'),
    mdi_image_filter_none('\uf399'),
    mdi_image_filter_tilt_shift('\uf39a'),
    mdi_image_filter_vintage('\uf39b'),
    mdi_import('\uf39c'),
    mdi_inbox('\uf39d'),
    mdi_information('\uf39e', false),
    mdi_information_outline('\uf39f', false),
    mdi_instagram('\uf3a0', false),
    mdi_instapaper('\uf3a1', false),
    mdi_internet_explorer('\uf3a2', false),
    mdi_invert_colors('\uf3a3'),
    mdi_jira('\uf3a4', false),
    mdi_jsfiddle('\uf3a5', false),
    mdi_keg('\uf3a6'),
    mdi_key('\uf3a7'),
    mdi_key_change('\uf3a8'),
    mdi_key_minus('\uf3a9'),
    mdi_key_plus('\uf3aa'),
    mdi_key_remove('\uf3ab'),
    mdi_key_variant('\uf3ac'),
    mdi_keyboard('\uf3ad'),
    mdi_keyboard_backspace('\uf3ae'),
    mdi_keyboard_caps('\uf3af'),
    mdi_keyboard_close('\uf3b0'),
    mdi_keyboard_off('\uf3b1'),
    mdi_keyboard_return('\uf3b2'),
    mdi_keyboard_tab('\uf3b3'),
    mdi_keyboard_variant('\uf3b4', false),
    mdi_label('\uf3b5'),
    mdi_label_outline('\uf3b6'),
    mdi_language_csharp('\uf3b7', false),
    mdi_language_css3('\uf3b8', false),
    mdi_language_html5('\uf3b9', false),
    mdi_language_javascript('\uf3ba', false),
    mdi_language_python('\uf3bb', false),
    mdi_language_python_text('\uf3bc', false),
    mdi_laptop('\uf3bd'),
    mdi_laptop_chromebook('\uf3be'),
    mdi_laptop_mac('\uf3bf'),
    mdi_laptop_windows('\uf3c0'),
    mdi_lastfm('\uf3c1', false),
    mdi_launch('\uf3c2'),
    mdi_layers('\uf3c3'),
    mdi_layers_off('\uf3c4'),
    mdi_leaf('\uf3c5'),
    mdi_library('\uf3c6'),
    mdi_library_books('\uf3c7', false),
    mdi_library_music('\uf3c8', false),
    mdi_library_plus('\uf3c9', false),
    mdi_lightbulb('\uf3ca'),
    mdi_lightbulb_outline('\uf3cb'),
    mdi_link('\uf3cc'),
    mdi_link_off('\uf3cd'),
    mdi_link_variant('\uf3ce'),
    mdi_link_variant_off('\uf3cf'),
    mdi_linkedin('\uf3d0', false),
    mdi_linkedin_box('\uf3d1', false),
    mdi_linux('\uf3d2', false),
    mdi_lock('\uf3d3'),
    mdi_lock_open('\uf3d4'),
    mdi_lock_open_outline('\uf3d5'),
    mdi_lock_outline('\uf3d6'),
    mdi_login('\uf3d7'),
    mdi_logout('\uf3d8'),
    mdi_looks('\uf3d9'),
    mdi_loupe('\uf3da', false),
    mdi_lumx('\uf3db', false),
    mdi_magnet('\uf3dc'),
    mdi_magnet_on('\uf3dd'),
    mdi_magnify('\uf3de', false),
    mdi_magnify_minus('\uf3df', false),
    mdi_magnify_plus('\uf3e0', false),
    mdi_mail_ru('\uf3e1', false),
    mdi_map('\uf3e2'),
    mdi_map_marker('\uf3e3'),
    mdi_map_marker_circle('\uf3e4'),
    mdi_map_marker_multiple('\uf3e5'),
    mdi_map_marker_off('\uf3e6'),
    mdi_map_marker_radius('\uf3e7'),
    mdi_margin('\uf3e8'),
    mdi_markdown('\uf3e9', false),
    mdi_marker_check('\uf3ea', false),
    mdi_martini('\uf3eb'),
    mdi_material_ui('\uf3ec', false),
    mdi_math_compass('\uf3ed'),
    mdi_maxcdn('\uf3ee', false),
    mdi_medium('\uf3ef', false),
    mdi_memory('\uf3f0'),
    mdi_menu('\uf3f1'),
    mdi_menu_down('\uf3f2'),
    mdi_menu_left('\uf3f3'),
    mdi_menu_right('\uf3f4'),
    mdi_menu_up('\uf3f5'),
    mdi_message('\uf3f6'),
    mdi_message_alert('\uf3f7'),
    mdi_message_draw('\uf3f8'),
    mdi_message_image('\uf3f9'),
    mdi_message_processing('\uf3fa'),
    mdi_message_reply('\uf3fb'),
    mdi_message_text('\uf3fc'),
    mdi_message_text_outline('\uf3fd'),
    mdi_message_video('\uf3fe'),
    mdi_microphone('\uf3ff'),
    mdi_microphone_off('\uf400'),
    mdi_microphone_outline('\uf401'),
    mdi_microphone_settings('\uf402'),
    mdi_microphone_variant('\uf403'),
    mdi_microphone_variant_off('\uf404'),
    mdi_minus('\uf405'),
    mdi_minus_box('\uf406'),
    mdi_minus_circle('\uf407'),
    mdi_minus_circle_outline('\uf408'),
    mdi_minus_network('\uf409'),
    mdi_monitor('\uf40a'),
    mdi_monitor_multiple('\uf40b'),
    mdi_more('\uf40c'),
    mdi_motorbike('\uf40d'),
    mdi_mouse('\uf40e'),
    mdi_mouse_off('\uf40f'),
    mdi_mouse_variant('\uf410'),
    mdi_mouse_variant_off('\uf411'),
    mdi_movie('\uf412', false),
    mdi_multiplication('\uf413'),
    mdi_multiplication_box('\uf414'),
    mdi_music_box('\uf415', false),
    mdi_music_box_outline('\uf416', false),
    mdi_music_circle('\uf417', false),
    mdi_music_note('\uf418', false),
    mdi_music_note_eighth('\uf419', false),
    mdi_music_note_half('\uf41a', false),
    mdi_music_note_off('\uf41b', false),
    mdi_music_note_quarter('\uf41c', false),
    mdi_music_note_sixteenth('\uf41d', false),
    mdi_music_note_whole('\uf41e', false),
    mdi_nature('\uf41f'),
    mdi_nature_people('\uf420'),
    mdi_navigation('\uf421'),
    mdi_needle('\uf422', false),
    mdi_nest_protect('\uf423', false),
    mdi_nest_thermostat('\uf424', false),
    mdi_newspaper('\uf425'),
    mdi_nfc('\uf426'),
    mdi_nfc_tap('\uf427'),
    mdi_nfc_variant('\uf428'),
    mdi_note('\uf429'),
    mdi_note_outline('\uf42a'),
    mdi_note_text('\uf42b'),
    mdi_numeric('\uf42c', false),
    mdi_numeric_0_box('\uf42d', false),
    mdi_numeric_0_box_multiple_outline('\uf42e', false),
    mdi_numeric_0_box_outline('\uf42f', false),
    mdi_numeric_1_box('\uf430', false),
    mdi_numeric_1_box_multiple_outline('\uf431', false),
    mdi_numeric_1_box_outline('\uf432', false),
    mdi_numeric_2_box('\uf433', false),
    mdi_numeric_2_box_multiple_outline('\uf434', false),
    mdi_numeric_2_box_outline('\uf435', false),
    mdi_numeric_3_box('\uf436', false),
    mdi_numeric_3_box_multiple_outline('\uf437', false),
    mdi_numeric_3_box_outline('\uf438', false),
    mdi_numeric_4_box('\uf439', false),
    mdi_numeric_4_box_multiple_outline('\uf43a', false),
    mdi_numeric_4_box_outline('\uf43b', false),
    mdi_numeric_5_box('\uf43c', false),
    mdi_numeric_5_box_multiple_outline('\uf43d', false),
    mdi_numeric_5_box_outline('\uf43e', false),
    mdi_numeric_6_box('\uf43f', false),
    mdi_numeric_6_box_multiple_outline('\uf440', false),
    mdi_numeric_6_box_outline('\uf441', false),
    mdi_numeric_7_box('\uf442', false),
    mdi_numeric_7_box_multiple_outline('\uf443', false),
    mdi_numeric_7_box_outline('\uf444', false),
    mdi_numeric_8_box('\uf445', false),
    mdi_numeric_8_box_multiple_outline('\uf446', false),
    mdi_numeric_8_box_outline('\uf447', false),
    mdi_numeric_9_box('\uf448', false),
    mdi_numeric_9_box_multiple_outline('\uf449', false),
    mdi_numeric_9_box_outline('\uf44a', false),
    mdi_numeric_9_plus_box('\uf44b', false),
    mdi_numeric_9_plus_box_multiple_outline('\uf44c', false),
    mdi_numeric_9_plus_box_outline('\uf44d', false),
    mdi_nutriton('\uf44e'),
    mdi_odnoklassniki('\uf44f', false),
    mdi_office('\uf450', false),
    mdi_oil('\uf451'),
    mdi_omega('\uf452', false),
    mdi_onedrive('\uf453', false),
    mdi_open_in_app('\uf454'),
    mdi_open_in_new('\uf455'),
    mdi_ornament('\uf456'),
    mdi_ornament_variant('\uf457'),
    mdi_outbox('\uf458'),
    mdi_owl('\uf459'),
    mdi_package('\uf45a'),
    mdi_package_down('\uf45b'),
    mdi_package_up('\uf45c'),
    mdi_package_variant('\uf45d'),
    mdi_package_variant_closed('\uf45e'),
    mdi_palette('\uf45f', false),
    mdi_palette_advanced('\uf460', false),
    mdi_panda('\uf461'),
    mdi_pandora('\uf462', false),
    mdi_panorama('\uf463'),
    mdi_panorama_fisheye('\uf464'),
    mdi_panorama_horizontal('\uf465'),
    mdi_panorama_vertical('\uf466'),
    mdi_panorama_wide_angle('\uf467'),
    mdi_paper_cut_vertical('\uf468'),
    mdi_paperclip('\uf469'),
    mdi_parking('\uf46a', false),
    mdi_pause('\uf46b'),
    mdi_pause_circle('\uf46c'),
    mdi_pause_circle_outline('\uf46d'),
    mdi_pause_octagon('\uf46e'),
    mdi_pause_octagon_outline('\uf46f'),
    mdi_paw('\uf470'),
    mdi_pen('\uf471', false),
    mdi_pencil('\uf472', false),
    mdi_pencil_box('\uf473', false),
    mdi_pencil_box_outline('\uf474', false),
    mdi_percent('\uf475'),
    mdi_pharmacy('\uf476', false),
    mdi_phone('\uf477'),
    mdi_phone_bluetooth('\uf478', false),
    mdi_phone_forward('\uf479'),
    mdi_phone_hangup('\uf47a'),
    mdi_phone_in_talk('\uf47b'),
    mdi_phone_incoming('\uf47c'),
    mdi_phone_locked('\uf47d'),
    mdi_phone_log('\uf47e'),
    mdi_phone_missed('\uf47f'),
    mdi_phone_outgoing('\uf480'),
    mdi_phone_paused('\uf481'),
    mdi_phone_settings('\uf482'),
    mdi_pig('\uf483'),
    mdi_pill('\uf484'),
    mdi_pin('\uf485'),
    mdi_pin_off('\uf486'),
    mdi_pine_tree('\uf487'),
    mdi_pine_tree_box('\uf488'),
    mdi_pinterest('\uf489', false),
    mdi_pinterest_box('\uf48a', false),
    mdi_pizza('\uf48b'),
    mdi_play('\uf48c', false),
    mdi_play_box_outline('\uf48d', false),
    mdi_play_circle('\uf48e', false),
    mdi_play_circle_outline('\uf48f', false),
    mdi_playlist_minus('\uf490'),
    mdi_playlist_plus('\uf491'),
    mdi_playstation('\uf492', false),
    mdi_plus('\uf493'),
    mdi_plus_box('\uf494'),
    mdi_plus_circle('\uf495'),
    mdi_plus_circle_outline('\uf496'),
    mdi_plus_network('\uf497'),
    mdi_plus_one('\uf498', false),
    mdi_pocket('\uf499'),
    mdi_poll('\uf49a'),
    mdi_poll_box('\uf49b'),
    mdi_polymer('\uf49c', false),
    mdi_popcorn('\uf49d'),
    mdi_pound('\uf49e', false),
    mdi_pound_box('\uf49f', false),
    mdi_power('\uf4a0'),
    mdi_power_settings('\uf4a1'),
    mdi_power_socket('\uf4a2'),
    mdi_presentation('\uf4a3'),
    mdi_presentation_play('\uf4a4', false),
    mdi_printer('\uf4a5', false),
    mdi_printer_3d('\uf4a6', false),
    mdi_pulse('\uf4a7'),
    mdi_puzzle('\uf4a8'),
    mdi_qrcode('\uf4a9'),
    mdi_quadcopter('\uf4aa'),
    mdi_quality_high('\uf4ab', false),
    mdi_quicktime('\uf4ac', false),
    mdi_radiator('\uf4ad'),
    mdi_radio('\uf4ae', false),
    mdi_radio_tower('\uf4af'),
    mdi_radioactive('\uf4b0'),
    mdi_radiobox_blank('\uf4b1'),
    mdi_radiobox_marked('\uf4b2'),
    mdi_raspberrypi('\uf4b3', false),
    mdi_rdio('\uf4b4', false),
    mdi_read('\uf4b5', false),
    mdi_readability('\uf4b6'),
    mdi_receipt('\uf4b7'),
    mdi_recycle('\uf4b8'),
    mdi_redo('\uf4b9'),
    mdi_redo_variant('\uf4ba'),
    mdi_refresh('\uf4bb'),
    mdi_relative_scale('\uf4bc', false),
    mdi_reload('\uf4bd', false),
    mdi_remote('\uf4be'),
    mdi_rename_box('\uf4bf', false),
    mdi_repeat('\uf4c0', false),
    mdi_repeat_off('\uf4c1', false),
    mdi_repeat_once('\uf4c2', false),
    mdi_replay('\uf4c3', false),
    mdi_reply('\uf4c4'),
    mdi_reply_all('\uf4c5'),
    mdi_reproduction('\uf4c6'),
    mdi_resize_bottom_right('\uf4c7', false),
    mdi_responsive('\uf4c8'),
    mdi_rewind('\uf4c9', false),
    mdi_ribbon('\uf4ca'),
    mdi_road('\uf4cb'),
    mdi_rocket('\uf4cc'),
    mdi_rotate_3d('\uf4cd'),
    mdi_rotate_left('\uf4ce', false),
    mdi_rotate_left_variant('\uf4cf', false),
    mdi_rotate_right('\uf4d0', false),
    mdi_rotate_right_variant('\uf4d1', false),
    mdi_routes('\uf4d2'),
    mdi_rss('\uf4d3'),
    mdi_rss_box('\uf4d4'),
    mdi_ruler('\uf4d5'),
    mdi_run('\uf4d6'),
    mdi_sale('\uf4d7'),
    mdi_satellite('\uf4d8'),
    mdi_satellite_variant('\uf4d9'),
    mdi_scale('\uf4da'),
    mdi_scale_bathroom('\uf4db'),
    mdi_school('\uf4dc'),
    mdi_screen_rotation('\uf4dd'),
    mdi_screen_rotation_lock('\uf4de'),
    mdi_script('\uf4df'),
    mdi_sd('\uf4e0', false),
    mdi_security('\uf4e1'),
    mdi_security_network('\uf4e2'),
    mdi_select('\uf4e3'),
    mdi_select_all('\uf4e4'),
    mdi_select_inverse('\uf4e5'),
    mdi_select_off('\uf4e6'),
    mdi_send('\uf4e7'),
    mdi_server('\uf4e8'),
    mdi_server_minus('\uf4e9'),
    mdi_server_network('\uf4ea'),
    mdi_server_network_off('\uf4eb'),
    mdi_server_off('\uf4ec'),
    mdi_server_plus('\uf4ed'),
    mdi_server_remove('\uf4ee'),
    mdi_server_security('\uf4ef'),
    mdi_settings('\uf4f0'),
    mdi_settings_box('\uf4f1'),
    mdi_shape_plus('\uf4f2'),
    mdi_share('\uf4f3'),
    mdi_share_variant('\uf4f4'),
    mdi_shield('\uf4f5'),
    mdi_shield_outline('\uf4f6'),
    mdi_shopping('\uf4f7'),
    mdi_shopping_music('\uf4f8', false),
    mdi_shuffle('\uf4f9', false),
    mdi_sigma('\uf4fa', false),
    mdi_sign_caution('\uf4fb'),
    mdi_signal('\uf4fc'),
    mdi_silverware('\uf4fd', false),
    mdi_silverware_fork('\uf4fe'),
    mdi_silverware_spoon('\uf4ff'),
    mdi_silverware_variant('\uf500', false),
    mdi_sim_alert('\uf501', false),
    mdi_sitemap('\uf502'),
    mdi_skip_next('\uf503', false),
    mdi_skip_previous('\uf504', false),
    mdi_skype('\uf505', false),
    mdi_skype_business('\uf506', false),
    mdi_sleep('\uf507', false),
    mdi_sleep_off('\uf508', false),
    mdi_smoking('\uf509'),
    mdi_smoking_off('\uf50a'),
    mdi_snapchat('\uf50b', false),
    mdi_snowman('\uf50c'),
    mdi_sofa('\uf50d'),
    mdi_sort('\uf50e'),
    mdi_sort_alphabetical('\uf50f', false),
    mdi_sort_ascending('\uf510'),
    mdi_sort_descending('\uf511'),
    mdi_sort_numeric('\uf512', false),
    mdi_sort_variant('\uf513'),
    mdi_soundcloud('\uf514', false),
    mdi_source_fork('\uf515'),
    mdi_source_pull('\uf516'),
    mdi_speaker('\uf517'),
    mdi_speaker_off('\uf518'),
    mdi_speedometer('\uf519', false),
    mdi_spellcheck('\uf51a', false),
    mdi_spotify('\uf51b', false),
    mdi_spotlight('\uf51c', false),
    mdi_spotlight_beam('\uf51d'),
    mdi_square_inc('\uf51e', false),
    mdi_square_inc_cash('\uf51f', false),
    mdi_stackoverflow('\uf520', false),
    mdi_star('\uf521'),
    mdi_star_circle('\uf522'),
    mdi_star_half('\uf523'),
    mdi_star_outline('\uf524'),
    mdi_steam('\uf525', false),
    mdi_stethoscope('\uf526'),
    mdi_stocking('\uf527'),
    mdi_stop('\uf528'),
    mdi_store('\uf529'),
    mdi_store_24_hour('\uf52a', false),
    mdi_stove('\uf52b'),
    mdi_subway('\uf52c'),
    mdi_sunglasses('\uf52d'),
    mdi_swap_horizontal('\uf52e'),
    mdi_swap_vertical('\uf52f'),
    mdi_swim('\uf530'),
    mdi_sword('\uf531', false),
    mdi_sync('\uf532'),
    mdi_sync_alert('\uf533'),
    mdi_sync_off('\uf534'),
    mdi_tab('\uf535'),
    mdi_tab_unselected('\uf536'),
    mdi_table('\uf537'),
    mdi_table_column_plus_after('\uf538'),
    mdi_table_column_plus_before('\uf539'),
    mdi_table_column_remove('\uf53a'),
    mdi_table_column_width('\uf53b'),
    mdi_table_edit('\uf53c', false),
    mdi_table_large('\uf53d'),
    mdi_table_row_height('\uf53e'),
    mdi_table_row_plus_after('\uf53f'),
    mdi_table_row_plus_before('\uf540'),
    mdi_table_row_remove('\uf541'),
    mdi_tablet('\uf542'),
    mdi_tablet_android('\uf543'),
    mdi_tablet_ipad('\uf544'),
    mdi_tag('\uf545'),
    mdi_tag_faces('\uf546'),
    mdi_tag_multiple('\uf547'),
    mdi_tag_outline('\uf548'),
    mdi_tag_text_outline('\uf549'),
    mdi_taxi('\uf54a'),
    mdi_teamviewer('\uf54b', false),
    mdi_telegram('\uf54c'),
    mdi_television('\uf54d'),
    mdi_television_guide('\uf54e'),
    mdi_temperature_celsius('\uf54f', false),
    mdi_temperature_fahrenheit('\uf550', false),
    mdi_temperature_kelvin('\uf551', false),
    mdi_tennis('\uf552'),
    mdi_tent('\uf553'),
    mdi_terrain('\uf554'),
    mdi_text_to_speech('\uf555'),
    mdi_text_to_speech_off('\uf556'),
    mdi_texture('\uf557'),
    mdi_theater('\uf558', false),
    mdi_theme_light_dark('\uf559'),
    mdi_thermometer('\uf55a'),
    mdi_thermometer_lines('\uf55b'),
    mdi_thumb_down('\uf55c'),
    mdi_thumb_down_outline('\uf55d'),
    mdi_thumb_up('\uf55e'),
    mdi_thumb_up_outline('\uf55f'),
    mdi_thumbs_up_down('\uf560'),
    mdi_ticket('\uf561'),
    mdi_ticket_account('\uf562'),
    mdi_tie('\uf563'),
    mdi_timelapse('\uf564', false),
    mdi_timer('\uf565', false),
    mdi_timer_10('\uf566', false),
    mdi_timer_3('\uf567', false),
    mdi_timer_off('\uf568', false),
    mdi_timer_sand('\uf569'),
    mdi_timetable('\uf56a', false),
    mdi_toggle_switch('\uf56b'),
    mdi_toggle_switch_off('\uf56c'),
    mdi_tooltip('\uf56d'),
    mdi_tooltip_edit('\uf56e', false),
    mdi_tooltip_image('\uf56f'),
    mdi_tooltip_outline('\uf570'),
    mdi_tooltip_outline_plus('\uf571'),
    mdi_tooltip_text('\uf572'),
    mdi_tor('\uf573', false),
    mdi_traffic_light('\uf574'),
    mdi_train('\uf575'),
    mdi_tram('\uf576'),
    mdi_transcribe('\uf577', false),
    mdi_transcribe_close('\uf578', false),
    mdi_transfer('\uf579'),
    mdi_tree('\uf57a'),
    mdi_trello('\uf57b', false),
    mdi_trending_down('\uf57c'),
    mdi_trending_neutral('\uf57d'),
    mdi_trending_up('\uf57e'),
    mdi_trophy('\uf57f'),
    mdi_trophy_award('\uf580'),
    mdi_trophy_variant('\uf581'),
    mdi_truck('\uf582'),
    mdi_tshirt_crew('\uf583'),
    mdi_tshirt_v('\uf584'),
    mdi_tumblr('\uf585', false),
    mdi_tumblr_reblog('\uf586'),
    mdi_twitch('\uf587', false),
    mdi_twitter('\uf588', false),
    mdi_twitter_box('\uf589', false),
    mdi_twitter_circle('\uf58a', false),
    mdi_twitter_retweet('\uf58b'),
    mdi_ubuntu('\uf58c', false),
    mdi_umbrella('\uf58d'),
    mdi_umbrella_outline('\uf58e'),
    mdi_undo('\uf58f'),
    mdi_undo_variant('\uf590'),
    mdi_unfold_less('\uf591'),
    mdi_unfold_more('\uf592'),
    mdi_ungroup('\uf593'),
    mdi_untappd('\uf594'),
    mdi_upload('\uf595'),
    mdi_usb('\uf596', false),
    mdi_vector_curve('\uf597'),
    mdi_vector_point('\uf598'),
    mdi_vector_square('\uf599'),
    mdi_verified('\uf59a', false),
    mdi_vibrate('\uf59b'),
    mdi_video('\uf59c'),
    mdi_video_off('\uf59d'),
    mdi_video_switch('\uf59e'),
    mdi_view_agenda('\uf59f'),
    mdi_view_array('\uf5a0'),
    mdi_view_carousel('\uf5a1'),
    mdi_view_column('\uf5a2'),
    mdi_view_dashboard('\uf5a3'),
    mdi_view_day('\uf5a4'),
    mdi_view_grid('\uf5a5'),
    mdi_view_headline('\uf5a6'),
    mdi_view_list('\uf5a7'),
    mdi_view_module('\uf5a8'),
    mdi_view_quilt('\uf5a9'),
    mdi_view_stream('\uf5aa'),
    mdi_view_week('\uf5ab'),
    mdi_vimeo('\uf5ac', false),
    mdi_vine('\uf5ad', false),
    mdi_vk('\uf5ae', false),
    mdi_vk_box('\uf5af', false),
    mdi_vk_circle('\uf5b0', false),
    mdi_voicemail('\uf5b1'),
    mdi_volume_high('\uf5b2'),
    mdi_volume_low('\uf5b3'),
    mdi_volume_medium('\uf5b4'),
    mdi_volume_off('\uf5b5'),
    mdi_vpn('\uf5b6'),
    mdi_walk('\uf5b7'),
    mdi_wallet('\uf5b8', false),
    mdi_wallet_giftcard('\uf5b9'),
    mdi_wallet_membership('\uf5ba'),
    mdi_wallet_travel('\uf5bb'),
    mdi_watch('\uf5bc'),
    mdi_watch_export('\uf5bd'),
    mdi_watch_import('\uf5be'),
    mdi_water('\uf5bf'),
    mdi_water_off('\uf5c0'),
    mdi_water_pump('\uf5c1'),
    mdi_weather_cloudy('\uf5c2'),
    mdi_weather_fog('\uf5c3'),
    mdi_weather_hail('\uf5c4'),
    mdi_weather_lightning('\uf5c5'),
    mdi_weather_night('\uf5c6'),
    mdi_weather_partlycloudy('\uf5c7'),
    mdi_weather_pouring('\uf5c8'),
    mdi_weather_rainy('\uf5c9'),
    mdi_weather_snowy('\uf5ca'),
    mdi_weather_sunny('\uf5cb'),
    mdi_weather_sunset('\uf5cc'),
    mdi_weather_sunset_down('\uf5cd'),
    mdi_weather_sunset_up('\uf5ce'),
    mdi_weather_windy('\uf5cf'),
    mdi_weather_windy_variant('\uf5d0'),
    mdi_web('\uf5d1'),
    mdi_webcam('\uf5d2'),
    mdi_weight('\uf5d3'),
    mdi_weight_kilogram('\uf5d4', false),
    mdi_whatsapp('\uf5d5', false),
    mdi_wheelchair_accessibility('\uf5d6'),
    mdi_white_balance_auto('\uf5d7', false),
    mdi_white_balance_incandescent('\uf5d8'),
    mdi_white_balance_irradescent('\uf5d9'),
    mdi_white_balance_sunny('\uf5da'),
    mdi_wifi('\uf5db'),
    mdi_wii('\uf5dc', false),
    mdi_wikipedia('\uf5dd', false),
    mdi_window_close('\uf5de'),
    mdi_window_closed('\uf5df'),
    mdi_window_maximize('\uf5e0'),
    mdi_window_minimize('\uf5e1'),
    mdi_window_open('\uf5e2'),
    mdi_window_restore('\uf5e3'),
    mdi_windows('\uf5e4', false),
    mdi_wordpress('\uf5e5', false),
    mdi_worker('\uf5e6'),
    mdi_wunderlist('\uf5e7', false),
    mdi_xbox('\uf5e8', false),
    mdi_xbox_controller('\uf5e9'),
    mdi_xbox_controller_off('\uf5ea'),
    mdi_xda('\uf5eb', false),
    mdi_xml('\uf5ec', false),
    mdi_yeast('\uf5ed', false),
    mdi_yelp('\uf5ee', false),
    mdi_youtube_play('\uf5ef', false),
    mdi_zip_box('\uf5f0');

    private final char character;
    private final boolean supportsRtl;

    MaterialCommunityIcons(char character) {
        this(character, true);
    }

    MaterialCommunityIcons(char character, boolean supportsRtl) {
        this.character = character;
        this.supportsRtl = supportsRtl;
    }

    @Override
    public String key() {
        return name().replace('_', '-');
    }

    @Override
    public char character() {
        return character;
    }

    @Override
    public boolean supportsRtl() {
        return supportsRtl;
    }
}
